project_id = "dztqvkyfnmnyhvmckxjc"

[functions.send-notification]
verify_jwt = false

[functions.send-bulk-email]
verify_jwt = true

[functions.track-email]
verify_jwt = false

[functions.process-scheduled-campaigns]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.process-workflows]
verify_jwt = false

[functions.send-whatsapp]
verify_jwt = true

[functions.trigger-workflow]
verify_jwt = false
